src/carts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = "carts"



urlpatterns = [
    path('', views.cart_home, name = "home"),
    path('update/', views.cart_update, name = "update"),
    path('checkout/', views.checkout_home, name = "checkout"),
    path('checkout/success', views.checkout_done, name = "success")
    
] 

src/products/urls.py
from django.urls import path

from .views import (
    ProductListView, 
    #product_list_view, 
    #ProductDetailView, 
    #product_detail_view,
    #ProductFeaturedDetailView,
    ProductSlugDetailView,
    #ProductFeaturedListView
    )

app_name = "products"

urlpatterns = [

    path('', ProductListView.as_view(), name = "list"),
    #path('featured/<int:pk>', ProductFeaturedDetailView.as_view()),
    #path('products-fbv/<slug:slug>', product_detail_view, name = "detail"),
    #path('products/<int:pk>', ProductDetailView.as_view()),
    path('<slug:slug>', ProductSlugDetailView.as_view(), name = "detail"),

] 

src/templates/base/css.html
{% load static %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel = "stylesheet" href = "{% static 'css/stripe-style.css' %}">

src/templates/base/js.html
{% load static %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/93c403ce82.js"></script>
    <script src="{% static 'js/csrf-ajax.js' %}"></script>
    <script src="{% static 'js/ecommerce.js' %}"></script>

    <!-- stripe-->
    <script src="https://js.stripe.com/v3/"></script>
    

src/templates/base/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as products_url %}
{% url 'login' as login_url %}
{% url 'logout' as logout_url %}
{% url 'register' as register_url %}
{% url "carts:home" as cart_url %}


<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{home_url}}">
    {% if brandname %}
        {{brandname}}
    {% else %}
    Ecommer
    {% endif %}
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item  {% if request.path == home_url %}active{% else %}{% endif %}">
        <a class="nav-link" href="{{home_url}}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% else %}{% endif %}">
        <a class="nav-link" href="{{contact_url}}">Contact</a>
      </li>
      <li class="nav-item {% if request.path == products_url %}active{% else %}{% endif %}">
        <a class="nav-link" href="{{products_url}}">Products</a>
      </li>
      {% if request.user.is_authenticated %}
        <li class="nav-item {% if request.path == logout_url %}active{% else %}{% endif %}">
            <a class="nav-link" href="{{logout_url}}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item {% if request.path == login_url %}active{% else %}{% endif %}">
            <a class="nav-link" href="{{login_url}}">Login</a>
        </li>
          <li class="nav-item {% if request.path == register_url %}active{% else %}{% endif %}">
            <a class="nav-link" href="{{register_url}}">Register</a>
        </li>
      {% endif %}
        <li class="nav-item {% if request.path == cart_url %}active{% else %}{% endif %}">
          <a class="nav-link" href="{{cart_url}}"><span class = "navbar-cart-count">{{request.session.cart_items}}</span> <i class = "fa fa-shopping-cart"></i> </a>
        </li>

    </ul>
    {% include "search/snippets/search-form.html" %}
  </div>
</nav>