src/carts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from . import views

app_name = "carts"



urlpatterns = [
    path('', views.cart_home, name = "home"),
    path('update/', views.cart_update, name = "update"),
    path('checkout/', views.checkout_home, name = "checkout"),
    path('checkout/success', views.checkout_done, name = "success")
    
] 

src/carts/models.py
from django.conf import settings
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed
import math


User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count()  == 1:
            new_obj = False
            #print("cart ID exists")
            cart_obj = qs.first()
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
            #print(cart_obj.id)

        else:
            new_obj = True
            cart_obj = self.new(user=request.user)
            request.session["cart_id"] = cart_obj.id
        return cart_obj, new_obj
        
    def new(self, user = None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, blank=True)
    total = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    subtotal = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    objects = CartManager()
    def __str__(self):
        return str(self.id)

def m2m_changed_cart_reciever(sender, instance, action,*args, **kwargs):
    #print(action)
    products = instance.products.all()
    if action == "post_remove" or action == "post_clear" or action=="post_add":
        total = 0 
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal =total
            instance.save()
m2m_changed.connect(m2m_changed_cart_reciever, sender=Cart.products.through)

def pre_save_cart_reciever(sender, instance, *args, **kwargs):
    instance.total = instance.subtotal

pre_save.connect(pre_save_cart_reciever, sender=Cart)

src/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from products.models import Product
from orders.models import Order
from .models import Cart
from accounts.forms import LoginForm, GuestForm
from adresses.forms import AdressForm
from adresses.models import Adress
from billing.models import BillingProfile
from accounts.models import GuestModel



def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id":x.id,
            "url":x.get_absolute_url(),
            "name":x.name, 
            "price":x.price
        } 
        for x in cart_obj.products.all()
    ] # [<object>, <object>]
    cart_data = {
        "products":products, 
        "subtotal":cart_obj.subtotal, 
        "total": cart_obj.total
    }
    return JsonResponse(cart_data)



def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    context = {"cart":cart_obj}
    return render(request, "carts/home.html", context)

def cart_update(request):
    product_id = request.POST.get("product_id")
    if product_id is not None:
        try:  
            product_obj = Product.objects.get(id=product_id)
        except ProductDoesNotExist:
            print("show me message to user, product has gone")
            return redirect("home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            added = True
            cart_obj.products.add(product_obj)
        request.session["cart_items"] = cart_obj.products.count()

        if request.is_ajax():
            print("ajax request")
            json_data = {
                "added":added,
                "removed":not added,
                "cartItemCount":cart_obj.products.count(),

            }
            return JsonResponse(json_data)
            #return JsonResponse({"message":"error 400"}, status_code=400) # Django rest framework
    return redirect("carts:home")

def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0: #or request.user.is_authenticated == False:
        return redirect("carts:home")

    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AdressForm()

    billing_adress_id = request.session.get("billing_adress_id", None)
    shipping_adress_id = request.session.get("shipping_adress_id", None)


    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    adress_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated:
            adress_qs = Adress.objects.filter(billing_profile = billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_adress_id:
            order_obj.shipping_adress = Adress.objects.get(id=shipping_adress_id)
            del request.session["shipping_adress_id"]
        elif billing_adress_id:
            order_obj.billing_adress = Adress.objects.get(id=billing_adress_id)
            del request.session["billing_adress_id"]
        if billing_adress_id or shipping_adress_id:
            order_obj.save()
    
    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            del request.session["cart_id"]
            request.session["cart_items"] = 0
            return redirect("carts:success")



    context = {
        "object":order_obj,
        "billing_profile":billing_profile,
        "login_form":login_form,
        "guest_form":guest_form,
        "address_form":address_form,
        "adress_qs":adress_qs
    }
    return render(request, "carts/checkout.html", context)


def checkout_done(request):
    return render(request, "carts/checkout-done.html")

src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}

{% block content %}
    <div class = "col-md-6 mx-auto py-5 text-center">
        <h1 class = "display-1">Thank you for your order! xd</h1>
    </div>
{% endblock content %}

src/carts/templates/carts/checkout.html
{% extends "base.html" %}

{% block content %}


    {% if not billing_profile %}
        <div class = "row">
            <div class = "col-md-6 text-center">
                <p> Login </p>
                {% include 'accounts/snippets/login-form.html' with form=login_form next_url=request.build_absolute_uri %}
            </div>
            <div class = "col-md-6 text-center">
                <p> Continue as guest</p>
                {% url "guest_register" as guest_register_url %}
                {% include 'accounts/snippets/login-form.html' with form=guest_form next_url=request.build_absolute_uri action_url=guest_register_url%}
            </div>
        </div>
    {% else %}
        {% if not object.shipping_adress %}
            <div class = "row">
                <div class = "col-md-6 mx-auto">
                    <p class = "lead">Shipping adress</p>
                    <hr>
                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'adresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='shipping'%}
                </div>
                <div class = "col-md-6">
                    {% url 'checkout_address_reuse' as checkout_address_reuse%}
                    {% include "adresses/prev_addresses.html" with adress_qs=adress_qs next_url=request.build_absolute_uri adress_type="shipping" action_url=checkout_address_reuse%}
                </div>
            </div>
        {% elif not object.billing_adress %}
                <div class = "row">
                    <div class = "col-md-6 mx-auto">
                        <p class = "lead">Billing adress</p>
                        <hr>
                {% url "checkout_address_create" as checkout_address_create %}
                {% include 'adresses/form.html' with form=address_form next_url=request.build_absolute_uri action_url=checkout_address_create address_type='billing'%}
                    </div>
                    <div class = "col-md-6">
                        {% url 'checkout_address_reuse' as checkout_address_reuse%}
                        {% include "adresses/prev_addresses.html" with adress_qs=adress_qs next_url=request.build_absolute_uri adress_type="billing" action_url=checkout_address_reuse%}
                    </div>
                </div>
        {% else %}
            <h1>Finalize Checkout yap</h1>
            <p>Cart items: {% for product in object.cart.products.all %}{{product}} {%if not forloop.last%},{%endif%}{% endfor %}</p>
            <p>Shipping address: {{object.shipping_adress.get_adress}}   
            <p>Billing address: {{object.billing_adress.get_adress}}   
            <p>Cart total: {{object.cart.total}}</p>
            <p>Shipping total: {{object.shipping_total}}</p>
            <p>Order total: {{object.total}}</p>
            <form class = "form" action="" method = "POST">{% csrf_token %}
                <input type = "submit" class = "btn btn-success" value = "ödeme yap">
            </form>
        {% endif %}





    {% endif %}


{% endblock content %}

src/carts/templates/carts/home.html
{% extends "base.html" %}

{% block content %}
<div class = "container">
    <div class = "row">
        <div class = "col-md-12">
            <h1>Cart</h1>
            {% if cart.products.exists %}

            <table class="table cart-home">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">Ürün adı</th>
                    <th scope="col">Ürün fiyatı</th>
                    <th scope="col">İşlem</th>
                    </tr>
                </thead>
                <tbody class="cart-body">
                    {% for product in cart.products.all %}
                        <tr class="cart-products">
                            <th scope="row">{{forloop.counter}}</th>
                            <td> <a href = "{{product.get_absolute_url}}">{% if product.image %}
                                <img src = "{{product.image.url}}" style = "width:30px;">
                            {% else %}

                            {% endif %} {{product.name}}</a></td>
                            <td>{{product.price}}</td>
                            <td>
                                {% include "carts/snippets/remove-product.html" with product_id=product.id%}
                            </td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
            <div class = "cart-item-remove-form">
                {% include "carts/snippets/remove-product.html"%}
            </div>


            <div class = "col-md-12">
                Subtotal: <span class = "cart-subtotal"> {{cart.subtotal}} ₺</span><br>
                Toplam: <span class = "cart-total">{{cart.total}} ₺</span>
                <br>
                <a href = "{% url 'carts:checkout' %}" class = "btn btn-lg btn-success">ÖDEME YAP</a>
            </div>  
            {% else %}
                Kartınız boş <a class = "btn btn-link">Alışveriş yapın</a>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}